### ISSUE TITLE
Debug Ethermint w/ Optimint crash on Mamaki

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/optimint#420]
When deploying an instance of Ethermint using Optimint v0.3.0 it made it 51 blocks before crashing. 

Error:

```
panic: close of closed channel

goroutine 881 [running]:
github.com/celestiaorg/optimint/rpc/json.(*service).Subscribe.func1()
	github.com/celestiaorg/optimint@v0.3.0/rpc/json/service.go:134 +0x33c
created by github.com/celestiaorg/optimint/rpc/json.(*service).Subscribe
	github.com/celestiaorg/optimint@v0.3.0/rpc/json/service.go:111 +0x3fb
```

**Comment by jbowen93** [comment]
Dupe of  https://github.com/celestiaorg/optimint/issues/419
