### ISSUE TITLE
Ethermint on Mamaki sequencer node crashes frequently

### ISSUE THREAD

**Issue by jbowen93** [celestiaorg/optimint#447]
The Ethermint sequencer node deployed on Mamaki crashes relatively frequently. This results in lost blocks (See https://github.com/celestiaorg/optimint/issues/437). We should figure out the root cause of the frequent crashes.

**Comment by tzdybal** [comment]
Any logs, stack traces, etc?
Do you have any monitoring tools on the sequencer machine to see memory consumption, etc?

**Comment by jbowen93** [comment]
This is caused by failing to submit a block
```
9:49AM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=18 module=BlockManager
9:49AM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=19 module=BlockManager
9:50AM ERR DA layer submission failed error="Codespace: 'sdk', Code: 19, Message: " attempt=20 module=BlockManager
panic: Failed to submit block to DA layer!
goroutine 179 [running]:
github.com/celestiaorg/optimint/block.(*Manager).submitBlockToDA(0xc0017786c0, {0x2bc7a58, 0xc000052060}, 0xc004de0540)
        github.com/celestiaorg/optimint@v0.3.2/block/manager.go:457 +0x41b
github.com/celestiaorg/optimint/block.(*Manager).publishBlock(0xc0017786c0, {0x2bc7a58, 0xc000052060})
        github.com/celestiaorg/optimint@v0.3.2/block/manager.go:398 +0x796
github.com/celestiaorg/optimint/block.(*Manager).AggregationLoop(0xc0017786c0, {0x2bc7a58, 0xc000052060})
        github.com/celestiaorg/optimint@v0.3.2/block/manager.go:169 +0x105
created by github.com/celestiaorg/optimint/node.(*Node).OnStart
        github.com/celestiaorg/optimint@v0.3.2/node/node.go:224 +0x28e

ethermintd.service: Main process exited, code=exited, status=2/INVALIDARGUMENT
ethermintd.service: Failed with result 'exit-code'.
ethermintd.service: Consumed 33.285s CPU time.
ethermintd.service: Scheduled restart job, restart counter is at 1.
Stopped ethermintd daemon.
ethermintd.service: Consumed 33.285s CPU time.
```

**Comment by jbowen93** [comment]
Specifically https://github.com/celestiaorg/optimint/blob/main/block/manager.go#L416

I think we should just return an error and handle it gracefully.

**Comment by jbowen93** [comment]
Naive implementation doesn't work
```
10:23AM ERR DA layer submission failed error="Post \"http://127.0.0.1:26658/submit_pfd\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)" attempt=20 module=BlockManager
10:24AM ERR Failed to submit block to DA Layer module=BlockManager
10:24AM ERR error while publishing block error="Failed to submit block to DA layer after 20 attempts" module=BlockManager
10:24AM INF Creating and publishing block height=41 module=BlockManager
10:24AM ERR error while publishing block error="block height mismatch" module=BlockManager
10:24AM INF Creating and publishing block height=42 module=BlockManager
10:24AM ERR error while publishing block error="block height mismatch" module=BlockManager
10:25AM INF Creating and publishing block height=43 module=BlockManager
10:25AM ERR error while publishing block error="block height mismatch" module=BlockManager
```
